language: go
go:
- 1.4
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get github.com/gato/aofgrep
script:
  - $HOME/gopath/bin/goveralls -v github.com/gato/aofgrep/filter -service=travis-ci -repotoken $COVERALLS_TOKEN
notifications:
  email:
    on_success: never
    on_failure: change